name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Configure Maven for GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
      run: |
        mkdir -p ~/.m2
        echo "<settings>
          <servers>
            <server>
              <id>github</id>
              <username>${{ github.actor }}</username>
              <password>${{ env.GITHUB_TOKEN }}</password>
            </server>
          </servers>
        </settings>" > ~/.m2/settings.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create Output Directory
      run: mkdir -p outTemp

    - name: Copy JAR to Output Directory
      run: cp target/*.jar outTemp/

    - name: Copy jPOS config file
      run: |
        cp jpos.xml outTemp/

    - name: Create Batch File in Output Directory
      run: |
        echo CLS > outTemp/start-application.bat
        echo @echo off >> out/start-application.bat
        echo Echo. >> out/start-application.bat
        echo Echo. >> out/start-application.bat
        echo Echo. >> out/start-application.bat
        echo Echo    Please wait while loading the application... >> out/start-application.bat
        echo Echo. >> out/start-application.bat
        echo Echo. >> out/start-application.bat
        echo java --enable-preview -jar fxp20-jpos-middleware.jar >> out/start-application.bat
        echo REM 2^>^&1 ^>NUL >> out/start-application.bat
        echo pause >> out/start-application.bat
        
    - name: Zip Output Directory
      run: zip -r package.zip outTemp

    - name: Publish Zip to GitHub Packages
      run: |
        curl -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
          -X PUT \
          -H "Content-Type: application/zip" \
          --data-binary @package.zip \
          https://maven.pkg.github.com/${{ github.repository_owner }}/maven-repo/package.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
